### ISSUE TITLE
Bad kubernets manifest

### ISSUE THREAD

**Issue by jefflowrey** [AcalephStorage/rudder#11]
I have been trying to use the kubernetes manifest file in the Deployment section (kind: Deployment), and was getting errors as follows:

**error validating "manifest.yaml": error validating data: expected type array, for field spec.template.spec.containers, got map; if you choose to ignore these errors, turn validation off with --validate=false**

I solved the issue by adding a - to change the contents of spec.template.spec.containers from a map to a sequence:

**&nbsp;&nbsp;&nbsp;&nbsp;spec:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;...
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;template:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;...
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;spec:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;containers:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;env:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;...**

**Comment by hunter** [comment]
Thanks for catching that @jefflowrey! I've updated the yaml and also bumped the version
